version: "3.7"
services:
  mock-service:
    stop_signal: SIGTERM
    stop_grace_period: 30s
    container_name: mock-service
    image: mock-service
    build:
      dockerfile: Dockerfile
      context: ./mock_service
    command: /entrypoint.sh
    env_file:
        - .env
    ports:
     - "8080:8080"
     - "8786:8786"

